trigger:
  - main  # Trigger the pipeline on pushes to the main branch

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Install_and_Build
    displayName: 'Install Dependencies and Build'
    jobs:
      - job: Install
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x' 
            displayName: 'Install Node.js'

          - script: npm ci
            displayName: 'Install npm packages'

          - script: npx playwright install --with-deps
            displayName: 'Install Playwright Browsers'

  - stage: Test
    displayName: 'Run Tests'
    jobs:
      - job: Run_Tests
        steps:
          - script: npm run test
            displayName: 'Run Playwright Tests'

          - task: PublishTestResults@2
            inputs:
              testResultsFiles: 'playwright-report/*.xml'
              testRunTitle: 'Playwright Tests'

  # - stage: Report
  #   displayName: 'Generate and Publish Report'
  #   jobs:
  #     - job: Generate_Report
  #       steps:
  #         - script: npm run report 
  #           displayName: 'Generate Cucumber Report'
            
  #         - task: PublishBuildArtifacts@1 
  #           inputs:
  #             pathtoPublish: 'cucumber-report' 
  #             artifactName: 'cucumber-report'
  # d     isplayName: 'Publish Cucumber Report'